print('===========================================================') 
print("                    Resume of Khushi Sharma                ")
print('===========================================================')
print("                   Name: Khushi Sharma                     ")
print('=============================================')
print("                   Age: 20                                 ")
print("                   City: New Delhi                         ")
print("                   Country: India                          ")
print("                   Email: khushi.sharma@gmail.com          ")
print("                   Phone: +91 9876543210                   ")
print("                   LinkedIn: https://www.linkedin.com/in/ks")
print("                   GitHub: https://github.com/khushi-sharma")
print("                   Portfolio: https://khushi-sharma.com    ")
print("                   Skills: Python, Machine Learning, AI     ")
print("                   Education: BE in CSE")
print('===========================================================')
print("                   Experience: 0 years                      ")
print('===========================================================')